routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\GroupController;
use App\Http\Controllers\Admin\TimetableController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    $group = \App\Models\Group::find(1);


    return $group->timetables;
//    return [$timetable->group, $timetable->day, $timetable->time, $timetable->course, $timetable->classroom, $timetable->instructor];
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::redirect('/panel', '/panel/profile/show')->name('panel.main.url');

///** Admin Panel */
//Route::get('panel/login', [LoginController::class, 'showPanelLoginForm'])->name('panel.login');

//Route::prefix('panel')->middleware(['auth', 'role:admin|manager'])->name('panel.')->group(function ($router) {
Route::prefix('panel')->middleware(['auth'])->name('panel.')->group(function ($router) {
    /** Profile */
    $router->prefix('profile')->name('profile.')->group(function ($router) {
        $router->get('show', [ProfileController::class, 'show'])->name('show');
        $router->get('edit', [ProfileController::class, 'edit'])->name('edit');
        $router->put('edit', [ProfileController::class, 'update'])->name('update');
        $router->put('updatePassword', [ProfileController::class, 'updatePassword'])->name('updatePassword');
    });
//
//    /** Users */
    $router->resource('users', UserController::class);
    $router->put('users/{user}/updatePassword', [UserController::class, 'updatePassword'])->name('users.update_password');


    /** Groups */
    Route::resource('groups', GroupController::class);

    /** Group's Timetable */
    Route::resource('groups/{group}/timetables', TimetableController::class);

//    $router->resourse('groups', GroupController::class);
//    /** Articles */
//    $router->resource('articles', ArticlesController::class);
//
//    /** Pages */
//    $router->resource('pages', PageController::class, ['except' => ['store', 'create']]);
//    $router->post('pages/{page}/worker/add', [PageController::class, 'addWorker'])->name('pages.worker.add');
//    $router->post('pages/{page}/worker/{worker}/delete', [PageController::class, 'deleteWorker'])->name('pages.worker.delete');
//
//    /** Workers */
//    $router->resource('workers', WorkerController::class);
//
//    /** Orders */
//    $router->resource('orders', OrderController::class);

    /** Roles */
    $router->resource('roles', RoleController::class);
//
//    /** Dictionaries */
//    $router->resource('dictionaries', DictionaryController::class);
//
//    /** Dictionary Items */
//    $router->resource('dictionaries/{dictionary}/items', DictionaryItemController::class, ['names' => 'dictionary-items']);
//
//    /** Membership Applications */
//    $router->resource('applications', MembershipApplicationController::class, ['except' => ['store', 'create']]);
//    $router->put('applications/{application}/accept', [MembershipApplicationController::class, 'accept'])->name('application.accept');
});

app/Http/Controllers/Admin/ProfileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class ProfileController extends Controller
{
    public function show(){
        $user = auth()->user();

        return view('admin.pages.profile.show', compact('user'));
    }

    public function edit(){
        $user = auth()->user();

        return view('admin.pages.profile.edit', compact('user'));
    }

    public function update(Request $request){
         Validator::make($request->all(), [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
        ])->after(function ($validator) {
            return redirect()->back()->withErrors($validator, 'updateProfile');
        });

        auth()->user()->update([
            'name' => $request->name,
            'email' => $request->email,
        ]);

        return redirect()->route('panel.profile.show', [\App::currentLocale()])->with('success', 'Данные успешно изменены');
    }

    public function updatePassword(Request $request){
        $user = auth()->user();

        if (\request('old_password') && Hash::check($request->old_password, $user->password)){
            Validator::make($request->all(), [
                'old_password' => 'required',
                'new_password' => 'required|different:old_password|min:8',
                'new_password_confirmation' => 'required|same:password'
            ])->after(function ($validator) {
                return redirect()->back()->withErrors($validator, 'updatePassword');
            });

            $user->update([
                'password' => $request->new_password
            ]);

            return redirect()->route('panel.profile.show', [\App::currentLocale()])->with('success', 'Данные успешно изменены');
        }

        return redirect()->back()->with('updatePassword', 'Пароль введен неправильно');
    }
}

resources/views/admin/pages/profile/edit.blade.php
@extends('admin.layouts.index')

@section('title', 'Профиль')

@section('content')

<div class="container container-fluid">
    <br>
    <ul class="breadcrumbs">
        <li><a href="{{route('panel.profile.show') }}" title="Профиль">Профиль</a></li>
        <li><span>{{$user->name}}</span></li>
    </ul>

    <form class="block" method="post" action="{{route('panel.profile.update') }}">
        @csrf
        @method('put')

        @if($errors->hasBag('updateProfile'))
            <div class="alert alert-danger">
                @foreach($errors->login as $error)
                    {{ $error }}<br>
                @endforeach
            </div>
        @endif

        <div class="tabs">
            <div class="mobile-dropdown">
                <div class="mobile-dropdown__title dynamic">Основная информация</div>
                <div class="mobile-dropdown__desc">
                    <ul class="tabs-titles">
                        <li class="active"><a href="javascript:;" title="Основная информация">Основная информация</a></li>
                    </ul>
                </div>
            </div>
            <div class="tabs-contents">
                <div class="active">
                    <div class="input-group">
                        <label class="input-group__title"> ФИО</label>
                        <input type="text" name="name" value="{{$user->name}}" placeholder="ФИО" class="input-regular"
                               data-required-text=">Пожалуйста, введите ФИО" required>
                    </div>
                    <br>
                    <div class="input-group">
                        <label class="input-group__title"> Почта</label>
                        <input type="email" name="email" value="{{$user->email}}" placeholder="Почта" class="input-regular"
                               data-required-text=">Пожалуйста, введите адрес электронной почты" required>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="buttons">
            <div>
                <button type="submit" class="btn btn--green">Сохранить</button>
            </div>
        </div>
    </form>

    <form class="block" method="post" action="{{route('panel.profile.updatePassword') }}">
        @csrf
        @method('put')

        <div class="tabs">
            <div class="mobile-dropdown">
                <div class="mobile-dropdown__title dynamic">Смена пароля</div>
                <div class="mobile-dropdown__desc">
                    <ul class="tabs-titles">
                        <li class="active"><a href="javascript:;" title="update_password">Смена пароля</a></li>
                    </ul>
                </div>
            </div>

            @if(session()->has('updatePassword'))
                <div class="alert alert-danger">
                    {{ session()->get('updatePassword') }}
                </div>
            @endif

            <div class="tabs-contents">
                <div class="active">
                    <div class="input-group">
                        <label class="input-group__title"> Текущий пароль</label>
                        <input type="password" name="old_password" class="input-regular" placeholder="Введите пароль"
                               data-required-text="Пожалуйста, введите свой пароль" data-validate="password" required>
                    </div>
                    <br>
                    <div class="input-group">
                        <label class="input-group__title"> Новый пароль</label>
                        <input type="password" name="new_password" class="input-regular" placeholder="Введите новый пароль"
                               data-required-text="Пожалуйста, введите новый пароль" data-validate="password" required>
                    </div>
                    <br>
                    <div class="input-group">
                        <label class="input-group__title"> Подтвердите Пароль</label>
                        <input type="password" name="new_password_confirmation" class="input-regular" placeholder="Подтвердите новый пароль"
                               data-required-text="Пожалуйста, подтвердите новый пароль" data-validate="password_confirmation" required>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="buttons">
            <div>
                <button type="submit" class="btn btn--green">Сохранить</button>
            </div>
        </div>
    </form>
</div>

@endsection
@section('scripts')
    <script>
        window.addEventListener('load', () => {
            let inputs = document.querySelectorAll('input[required]');

            for(let i = 0; i < inputs.length; i++) {
                inputs[i].addEventListener('invalid', () => {
                    let msg = inputs[i].getAttribute('data-required-text');
                    inputs[i].setCustomValidity(msg);
                })
                inputs[i].addEventListener('input', () => {
                    inputs[i].setCustomValidity('');
                })
            }
        });
    </script>

@endsection

resources/views/admin/pages/profile/show.blade.php
@extends('admin.layouts.index')

@section('title', 'Профиль')

@section('content')

<div class="container container-fluid">
    <ul class="breadcrumbs">
        <li><span>Профиль</span></li>
        <li><span>{{$user->name}}</span></li>
    </ul>

    <div class="fund-header">
        <div class="fund-header__left">
            <div class="fund-header__id">#{{$user->id}}</div>
            <h1 class="fund-header__title">{{$user->name}}</h1>
        </div>
        <div class="fund-header__right">
            <div class="property">
                <div class="property__title">Дата создания</div>
                <div class="property__text">{{$user->created_at}}</div>
            </div>
            <div class="property">
                <div class="property__title">Дата изменения</div>
                <div class="property__text">{{$user->updated_at}}</div>
            </div>
        </div>
    </div>

    <div class="block">
        <div class="tabs">
            <div class="mobile-dropdown">
                <div class="mobile-dropdown__title dynamic">Основная информация</div>
                <div class="mobile-dropdown__desc">
                    <ul class="tabs-titles">
                        <li class="active"><a href="javascript:;" title="Основная информация">Основная информация</a></li>
                    </ul>
                </div>
            </div>
            <div class="tabs-contents">
                <div class="active">
                    @if(session()->has('success'))
                        <div class="alert alert-success">
                            {{ session()->get('success') }}
                        </div>
                    @endif

                    @if($errors->hasBag('updateProfile'))
                        <div class="alert alert-danger">
                            @foreach($errors->login as $error)
                                {{ $error }}<br>
                            @endforeach
                        </div>
                    @endif

                    <div class="input-group">
                        <label class="input-group__title"> ФИО</label>
                        <input type="text" name="name" value="{{$user->name}}" placeholder="ФИО" class="input-regular" disabled>
                    </div>
                    <br>
                    <div class="input-group">
                        <label class="input-group__title"> Почта</label>
                        <input type="email" name="email" value="{{$user->email}}" placeholder="Почта" class="input-regular" disabled>
                    </div>
                    <br>
                    <div class="input-group">
                        <label class="input-group__title"> Роль</label>
                        <input type="text" name="role" value="{{$user->roles[0]->name}}" placeholder="Роль" class="input-regular" disabled>
                    </div>
                    <br>
                    <div class="input-group">
                        <a class="btn btn-primary" href="{{ route('panel.profile.edit') }}" title="Редактировать">Редактировать</a>
                    </div>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection