routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\GroupController;
use App\Http\Controllers\Admin\TimetableController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    $group = \App\Models\Group::find(1);


    return $group->timetables;
//    return [$timetable->group, $timetable->day, $timetable->time, $timetable->course, $timetable->classroom, $timetable->instructor];
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::redirect('/panel', '/panel/profile/show')->name('panel.main.url');

///** Admin Panel */
//Route::get('panel/login', [LoginController::class, 'showPanelLoginForm'])->name('panel.login');

//Route::prefix('panel')->middleware(['auth', 'role:admin|manager'])->name('panel.')->group(function ($router) {
Route::prefix('panel')->middleware(['auth'])->name('panel.')->group(function ($router) {
    /** Profile */
    $router->prefix('profile')->name('profile.')->group(function ($router) {
        $router->get('show', [ProfileController::class, 'show'])->name('show');
        $router->get('edit', [ProfileController::class, 'edit'])->name('edit');
        $router->put('edit', [ProfileController::class, 'update'])->name('update');
        $router->put('updatePassword', [ProfileController::class, 'updatePassword'])->name('updatePassword');
    });
//
//    /** Users */
    $router->resource('users', UserController::class);
    $router->put('users/{user}/updatePassword', [UserController::class, 'updatePassword'])->name('users.update_password');


    /** Groups */
    Route::resource('groups', GroupController::class);

    /** Group's Timetable */
    Route::resource('groups/{group}/timetables', TimetableController::class);

//    $router->resourse('groups', GroupController::class);
//    /** Articles */
//    $router->resource('articles', ArticlesController::class);
//
//    /** Pages */
//    $router->resource('pages', PageController::class, ['except' => ['store', 'create']]);
//    $router->post('pages/{page}/worker/add', [PageController::class, 'addWorker'])->name('pages.worker.add');
//    $router->post('pages/{page}/worker/{worker}/delete', [PageController::class, 'deleteWorker'])->name('pages.worker.delete');
//
//    /** Workers */
//    $router->resource('workers', WorkerController::class);
//
//    /** Orders */
//    $router->resource('orders', OrderController::class);

    /** Roles */
    $router->resource('roles', RoleController::class);
//
//    /** Dictionaries */
//    $router->resource('dictionaries', DictionaryController::class);
//
//    /** Dictionary Items */
//    $router->resource('dictionaries/{dictionary}/items', DictionaryItemController::class, ['names' => 'dictionary-items']);
//
//    /** Membership Applications */
//    $router->resource('applications', MembershipApplicationController::class, ['except' => ['store', 'create']]);
//    $router->put('applications/{application}/accept', [MembershipApplicationController::class, 'accept'])->name('application.accept');
});

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Group
 *
 * @property int $id
 * @property string $title
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Timetable[] $timetables
 * @property-read int|null $timetables_count
 * @method static \Illuminate\Database\Eloquent\Builder|Group newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Group newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Group query()
 * @method static \Illuminate\Database\Eloquent\Builder|Group whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Group whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Group whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Group whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Group extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'title'
    ];

    public function timetables()
    {
        return $this->hasMany(Timetable::class);
    }
}

app/Http/Controllers/Admin/GroupController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Group;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $groups = Group::paginate(10);

        return view('admin.pages.groups.index', compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.pages.groups.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $group = Group::create([
            'title' => $request->title
        ]);

        return redirect()->route('panel.groups.show', $group)->with('success','Group created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param Group $group
     * @return Application|Factory|View
     */
    public function show(Group $group)
    {
        return view('admin.pages.groups.show', compact('group'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Group $group
     * @return Application|Factory|View
     */
    public function edit(Group $group)
    {
        return view('admin.pages.groups.edit', compact('group'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Group $group
     * @return Application|Redirector|RedirectResponse
     */
    public function update(Request $request, Group $group)
    {
        $group->update($request->all());

        return redirect(route('panel.groups.show', $group))->with('success','Group updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Group $group
     * @return Application|Redirector|RedirectResponse
     */
    public function destroy(Group $group)
    {
        $group->forceDelete();

        return redirect( route('panel.groups.index'))->with('success', 'Group deleted successfully');
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Models\Group;
use Illuminate\Http\Request;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function show(Group $group)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function edit(Group $group)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Group $group)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function destroy(Group $group)
    {
        //
    }
}

resources/views/admin/pages/groups/create.blade.php
@extends('admin.layouts.index')

@section('title', 'Новости')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.articles.index') }}">Управление новостями</a></li>
                    <li><span>Добавить новость</span></li>
                </ul>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.articles.index', [ 'lang' => \request()->segment(1) ]) }}">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block">
        @can('article-create')
        <form method="post" action="{{route('panel.articles.store') }}" enctype="multipart/form-data">
            @csrf
            <h2 class="title-primary">Новость</h2>
            <div class="tabs">
                <div class="mobile-dropdown">
                    <div class="mobile-dropdown__title dynamic">Рус</div>
                    <div class="mobile-dropdown__desc">
                        <ul class="tabs-titles">
                            <li class="active"><a href="javascript:;" title="Рус">Рус</a></li>
                            <li><a href="javascript:;" id="" title="Қаз">Қаз</a></li>
                            <li><a href="javascript:;" id="" title="Қаз">Eng</a></li>
                        </ul>
                    </div>
                </div>
                <div class="tabs-contents">
                    <div class="active">
                        <div class="input-group">
                            <label class="input-group__title">Название <span class="required">*</span></label>
                            <input type="text" name="title_ru" placeholder="Название" class="input-regular">
                        </div>
                        <br>
                        <div class="input-group">
                            <div class="input-group__title">Описание <span class="required">*</span></div>
                            <textarea name="description_ru" class="tinymce-text-here input-regular"></textarea>
                        </div>
                    </div>
                    <div>
                        <div class="input-group">
                            <label class="input-group__title">Атауы <span class="required">*</span></label>
                            <input type="text" name="title_kk" placeholder="Название" class="input-regular">
                        </div>
                        <br>
                        <div class="input-group">
                            <div class="input-group__title">Сипаттамасы <span class="required">*</span></div>
                            <textarea name="description_kk" class="tinymce-text-here input-regular"></textarea>
                        </div>
                    </div>
                    <div>
                        <div class="input-group">
                            <label class="input-group__title">Title <span class="required">*</span></label>
                            <input type="text" name="title_en" placeholder="Название" class="input-regular">
                        </div>
                        <br>
                        <div class="input-group">
                            <div class="input-group__title">Description <span class="required">*</span></div>
                            <textarea name="description_en" class="tinymce-text-here input-regular" ></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-sm-6">
                    <div class="input-group">
                        <label class="checkbox">
                            <input type="checkbox" name="is_published" value="1">
                            <span>Опубликовано</span>
                        </label>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="input-group">
                        <label class="input-group__title">Дата публикации</label>
                        <label class="time">
                            <input type="text" name="published_at" value="" placeholder=""
                                   class="input-regular custom-datepicker">
                        </label>
                    </div>
                </div>
            </div>
            <div class="input-group">
                <label class="input-group__title">Для кого</label>
                <select name="type" class="input-regular chosen" data-placeholder="">
                    <option value="1">Общедоступный</option>
                    <option value="2">Авторизованным</option>
                    <option value="3">Для членов МСК</option>
                </select>
            </div>
            <div class="input-group">
                <label class="input-group__title">Категория</label>
                <select name="category_id" class="input-regular chosen" data-placeholder="" required>
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <label class="input-group__title">Фото</label>
                    <input type="file" name="image" class="form-control" placeholder="image">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </form>
        @endcan
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
        <script src="https://cdn.tiny.cloud/1/eutvjr9zyhc4qtchwyfwhutknw2iunsf80kiuye2fdomu2wd/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
        <script src="/admin/js/api.js"></script>
        <script src="/admin/js/tinymce.js"></script>
    <!---->
@endsection

resources/views/admin/pages/groups/edit.blade.php
@extends('admin.layouts.index')

@section('title', 'Новости')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.groups.index') }}">Groups</a></li>
                    <li><a href="{{ route('panel.groups.show', $group) }}">{{ $group->title }}</a></li>
                    <li><span>Редактировать</span></li>
                </ul>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.groups.index') }}">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block">
        <form method="post" action="{{route('panel.groups.update', $group) }}" enctype="multipart/form-data">
            @csrf
            @method('put')


            <h2 class="title-primary">Group</h2>
            <div class="tabs">
                <div class="tabs-contents">
                    <div class="active">
                        <div class="input-group">
                            <label class="input-group__title">Title</label>
                            <input type="text" name="title" placeholder="Title"
                                   class="input-regular" value="{{ $group->title }}">
                        </div>
                    </div>
                </div>
            </div>

            <div class="input-group">
                <label class="input-group__title">Date of publishing</label>
                <input type="text" name="created_at" title="Опубликован" class="input-regular"
                       value="{{ $group->created_at ?? '-' }}">
            </div>


            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn--green">Save</button>
                    @can('record-delete')
                        <a class="btn btn-danger btn--red" href="{{ route('panel.groups.destroy', $group->id) }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('delete-form').submit();" title="Удалить">Delete
                        </a>
                    @endcan
                </div>
            </div>
        </form>
        @can('group-delete')
            <form id="delete-form" action="{{ route('panel.groups.destroy', $group->id) }}" method="POST" class="d-none">
                @csrf
                @method('DELETE')
            </form>
        @endcan
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <script src="https://cdn.tiny.cloud/1/eutvjr9zyhc4qtchwyfwhutknw2iunsf80kiuye2fdomu2wd/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="/admin/assets/api.js"></script>
    <script src="/admin/assets/js/tinymce.js"></script>
    <!---->
@endsection

resources/views/admin/pages/groups/index.blade.php
@extends('admin.layouts.index')

@section('title', 'Новости')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <h1 class="title-primary" style="margin-bottom: 0">Groups</h1>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div>
                        @can('record-create')
                            <a class="btn btn-success" href="{{ route('panel.groups.create') }}">Add group</a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <br>
    <div class="block">
        <h2 class="title-secondary">Список новостей</h2>
        <table class="table table-records">
            <colgroup>
                <col span="1" style="width: 3%;">
                <col span="1" style="width: 40%;">
                <col span="1" style="width: 17.5%;">
                <col span="1" style="width: 17.5%;">
            </colgroup>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Название</th>
                    <th>Опубликован</th>
                    <th>Дата публикации</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($groups as $group)
                    <tr>
                        <td>{{ $group->id }}</td>
                        <td>{{ $group->title }}</td>
                        <td>{{ $group->created_at ?? '-'}}</td>
                        <td>{{ $group->updated_at ?? '-' }}</td>
                        <td>
                            <a class="icon-btn icon-btn--green icon-eye" href="{{ route('panel.groups.show', $group->id) }}" title="Смотреть"></a>
                            @can('record-edit')
                                <a class="icon-btn icon-btn--yellow icon-edit" href="{{ route('panel.groups.edit', $group->id) }}" title="Редактировать"></a>
                            @endcan
                            @can('record-delete')
                                <a href="javascript:;" title="Удалить"
                                   onclick="document.querySelector('#model-{{ $group->id }}').submit()"
                                   class="icon-btn icon-btn--pink icon-delete"></a>
                                <form action="{{ route('panel.groups.destroy',  $group->id) }}" id="model-{{ $group->id }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            @endcan
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        {{ $groups->appends(\Illuminate\Support\Facades\Request::except('page'))->links("vendor.pagination.admin") }}
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection

resources/views/admin/pages/groups/show.blade.php
@extends('admin.layouts.index')

@section('title', 'Новости')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-8">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.groups.index') }}">Groups</a></li>
                    <li><span>{{ $group->title }}</span></li>
                </ul>
            </div>
            <div class="col-md-4 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary btn--green" href="{{ route('panel.timetables.index', $group->id) }}">Timetable</a>
                    </div>

                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.groups.index') }}">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="block">
        <h2 class="title-primary">Group</h2>
        <div class="tabs">
            <div class="tabs-contents">
                <div class="active">
                    <div class="input-group">
                        <label class="input-group__title">Title</label>
                        <input type="text" name="title_ru" placeholder="Title"
                               class="input-regular" value="{{ $group->title }}" disabled>
                    </div>
                </div>
            </div>
        </div>
        <div class="input-group">
            <label class="input-group__title">Date of publishing</label>
            <input type="text" name="published_at" title="Опубликован" class="input-regular"
                   value="{{ $group->created_at ?? '-' }}" disabled>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                @can('record-edit')
                    <a class="btn btn-primary" href="{{ route('panel.groups.edit', $group->id) }}">Редактировать</a>
                @endcan
                @can('record-delete')
                    <a class="btn btn-danger btn--red" href="{{ route('panel.groups.destroy', $group->id) }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('delete-form').submit();" title="Удалить">Удалить
                    </a>
                    <form id="delete-form" action="{{ route('panel.groups.destroy', $group->id) }}" method="POST" class="d-none">
                        @csrf
                        @method('DELETE')
                    </form>
                @endcan
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection