routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\GroupController;
use App\Http\Controllers\Admin\TimetableController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    $group = \App\Models\Group::find(1);


    return $group->timetables;
//    return [$timetable->group, $timetable->day, $timetable->time, $timetable->course, $timetable->classroom, $timetable->instructor];
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::redirect('/panel', '/panel/profile/show')->name('panel.main.url');

///** Admin Panel */
//Route::get('panel/login', [LoginController::class, 'showPanelLoginForm'])->name('panel.login');

//Route::prefix('panel')->middleware(['auth', 'role:admin|manager'])->name('panel.')->group(function ($router) {
Route::prefix('panel')->middleware(['auth'])->name('panel.')->group(function ($router) {
    /** Profile */
    $router->prefix('profile')->name('profile.')->group(function ($router) {
        $router->get('show', [ProfileController::class, 'show'])->name('show');
        $router->get('edit', [ProfileController::class, 'edit'])->name('edit');
        $router->put('edit', [ProfileController::class, 'update'])->name('update');
        $router->put('updatePassword', [ProfileController::class, 'updatePassword'])->name('updatePassword');
    });
//
//    /** Users */
    $router->resource('users', UserController::class);
    $router->put('users/{user}/updatePassword', [UserController::class, 'updatePassword'])->name('users.update_password');


    /** Groups */
    Route::resource('groups', GroupController::class);

    /** Group's Timetable */
    Route::resource('groups/{group}/timetables', TimetableController::class);

//    $router->resourse('groups', GroupController::class);
//    /** Articles */
//    $router->resource('articles', ArticlesController::class);
//
//    /** Pages */
//    $router->resource('pages', PageController::class, ['except' => ['store', 'create']]);
//    $router->post('pages/{page}/worker/add', [PageController::class, 'addWorker'])->name('pages.worker.add');
//    $router->post('pages/{page}/worker/{worker}/delete', [PageController::class, 'deleteWorker'])->name('pages.worker.delete');
//
//    /** Workers */
//    $router->resource('workers', WorkerController::class);
//
//    /** Orders */
//    $router->resource('orders', OrderController::class);

    /** Roles */
    $router->resource('roles', RoleController::class);
//
//    /** Dictionaries */
//    $router->resource('dictionaries', DictionaryController::class);
//
//    /** Dictionary Items */
//    $router->resource('dictionaries/{dictionary}/items', DictionaryItemController::class, ['names' => 'dictionary-items']);
//
//    /** Membership Applications */
//    $router->resource('applications', MembershipApplicationController::class, ['except' => ['store', 'create']]);
//    $router->put('applications/{application}/accept', [MembershipApplicationController::class, 'accept'])->name('application.accept');
});

resources/views/admin/layouts/partials/footer.blade.php
<footer class="footer">
</footer>

resources/views/admin/layouts/partials/head.blade.php
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width">
<title>@yield('title','Admin Panel') - Meatunion Admin Panel</title>

<link rel="stylesheet" href="/admin/libs/fancybox/dist/jquery.fancybox.min.css" type="text/css" media="screen"/>
<link rel="stylesheet" href="/admin/libs/chosen/chosen.css" type="text/css" media="screen"/>
<link rel="stylesheet" href="/admin/libs/air-datepicker/dist/css/datepicker.css" type="text/css" media="screen"/>
<link rel="stylesheet" href="/admin/css/style.css" type="text/css" media="screen"/>

<link rel="apple-touch-icon" sizes="180x180" href="/admin/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/admin/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/admin/favicon/favicon-16x16.png">
<link rel="manifest" href="/admin/favicon/site.webmanifest">
<link rel="mask-icon" href="/admin/favicon/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

<meta name="title" content="Заголовок">
<meta name="description" content="Описание">
<meta name="keywords" content="">
<meta property="og:type" content="article">
<meta property="og:title" content="Заголовок">
<meta property="og:description" content="Описание">
<meta property="og:url" content="/">
<meta property="og:image" content="/admin/img/og-image.jpg">
<meta property="og:site_name" content="localhost:9876">
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:title" content="Заголовок">
<meta property="twitter:description" content="Описание">
<meta property="twitter:image" content="/admin/img/og-image.jpg">
<meta property="twitter:site" content="">
<meta property="twitter:creator" content="">
<meta property="twitter:url" content="/">
<meta property="author" content="">
<meta name="relap-image" content="/admin/img/og-image.jpg">
<meta name="relap-title" content="Заголовок">
<meta name="relap-description" content=" ">

resources/views/admin/layouts/partials/header.blade.php
<header class="header">
    <div class="container container-fluid">
        <a href="javascript:;" title="Свернуть/развернуть навигацию" class="menu-btn icon-menu"></a>
        <a href="/" title="Главная" class="logo hidden-md hidden-lg"><img src="/admin/img/logo_light.svg" alt=""></a>
        <div class="language hidden-sm hidden-xs">
{{--            <a href="{{ route('switchLang', [$lang, 'ru']) }}" title="РУС" class="{{ $lang == "ru" ? 'active' : '' }}">РУС</a>--}}
{{--            <a href="{{ route('switchLang', [$lang, 'en']) }}" title="ENG" class="{{ $lang == "en" ? 'active' : '' }}">ENG</a>--}}
{{--            <a href="{{ route('switchLang', [$lang, 'kk']) }}" title="Қаз" class="{{ $lang == "kk" ? 'active' : '' }}">Қаз</a>--}}
        </div>
        <div class="header-dropdown account-nav">
            <div class="header-dropdown__title">
{{--                <span> @lang('admin/partials.header.welcome'), Илья!</span> <img src="/admin/img/user.svg" alt=""> <i--}}
                <span> Добро пожаловать, {{ auth()->user()->name }}</span> <img src="/admin/img/user.svg" alt=""> <i
                    class="icon-chevron-down"></i>
            </div>
            <div class="header-dropdown__desc">
                <ul>
{{--                    <li class="language hidden-md hidden-lg">--}}
{{--                        <a href="{{ route('switchLang', [$lang, 'ru']) }}" title="РУС" class="active">РУС</a>--}}
{{--                        <a href="{{ route('switchLang', [$lang, 'en']) }}" title="ENG">ENG</a>--}}
{{--                        <a href="{{ route('switchLang', [$lang, 'kk']) }}" title="Қаз">Қаз</a>--}}
{{--                    </li>--}}
                    <li>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

resources/views/admin/layouts/partials/modals.blade.php
<div id="message" class="modal" style="display: none;">
    <h4 class="title-secondary">Удаление</h4>
    <div class="plain-text">
        При удалении все данные будут удалены
    </div>
    <hr>
    <div class="buttons justify-end">
        <div><button class="btn btn--red">Удалить</button></div>
        <div><button class="btn" data-fancybox-close>Отмена</button></div>
    </div>
</div>

resources/views/admin/layouts/partials/scripts.blade.php
<script src="/admin/libs/jquery/dist/jquery.js"></script>
<script src="/admin/libs/maskedinput/maskedinput.js"></script>
<script src="/admin/libs/fancybox/dist/jquery.fancybox.min.js"></script>
<script src="/admin/libs/chosen/chosen.jquery.js"></script>
<script src="/admin/libs/air-datepicker/dist/js/datepicker.js"></script>
<script type="text/javascript" src="/admin/libs/plupload/js/plupload.full.min.js"></script>
<script src="/admin/js/scripts.js"></script>

resources/views/admin/layouts/partials/sidebar.blade.php
<aside class="sidebar">
    <div class="sidebar__top hidden-sm hidden-xs">
        <a href="/" title="Главная" class="logo"><img src="/admin/img/admin_panel_logo.jpeg" alt=""></a>
    </div>
    <div class="menu-wrapper">
        <ul class="menu">
            <li class="dropdown">
                <a href="javascript:;" title="Профиль"><i class="icon-directory"></i>Профиль</a>
                <ul>
                    <li><a href="{{ route('panel.profile.show') }}" title="Смотреть">Смотреть</a></li>
                    <li><a href="{{ route('panel.profile.edit') }}" title="Редактировать">Редактировать</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="javascript:;" title="Roles"><i class="icon-users"></i>Роли</a>
                <ul>
                    <li><a class="nav-link" href="{{ route('panel.roles.index') }}">Список ролей</a></li>
                    <li><a href="{{ route('panel.roles.create') }}" title="Добавить" class="add">+Добавить</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="javascript:;" title="Groups"><i class="icon-users"></i>Groups</a>
                <ul>
                    <li><a class="nav-link" href="{{ route('panel.groups.index') }}">List -of groups</a></li>
                    <li><a href="{{ route('panel.groups.create') }}" title="Добавить" class="add">+Add</a></li>
                </ul>
            </li>
            <li class="dropdown">--}}
{{--                <a href="javascript:;" title="@lang('admin/partials.sidebar.articles')"><i class="icon-users"></i>Новости</a>--}}
{{--                <ul>--}}
{{--                    <li><a class="nav-link" href="{{ route('panel.articles.index') }}">Список новостей</a></li>--}}
{{--                    <li><a href="{{ route('panel.articles.create') }}" title="Добавить" class="add">+Добавить</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
            <li class="dropdown">
                <a href="javascript:;" title="Страницы"><i class="icon-users"></i>Пользователи</a>
                <ul>
                    <li><a class="nav-link" href="{{ route('panel.users.index') }}">Все пользователи</a></li>
                    <li><a href="{{ route('panel.users.create') }}" title="Добавить" class="add">+Добавить пользователя</a></li>
                </ul>
            </li>
{{--            <li class="dropdown">--}}
{{--                <a href="javascript:;" title="Страницы"><i class="icon-users"></i>Страницы</a>--}}
{{--                <ul>--}}
{{--                    <li><a class="nav-link" href="{{ route('panel.pages.index') }}">Список страниц</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
{{--            <li class="dropdown">--}}
{{--                <a href="javascript:;" title="Страницы"><i class="icon-users"></i>Сотрудники</a>--}}
{{--                <ul>--}}
{{--                    <li><a class="nav-link" href="{{ route('panel.workers.index') }}">Список сотрудников</a></li>--}}
{{--                    <li><a href="{{ route('panel.workers.create') }}" title="Добавить" class="add">+Добавить</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
{{--            <li class="dropdown">--}}
{{--                <a href="javascript:;" title="Страницы"><i class="icon-users"></i>Заявки</a>--}}
{{--                <ul>--}}
{{--                    <li><a class="nav-link" href="{{ route('panel.orders.index') }}">Список заявок</a></li>--}}
{{--                    <li><a href="{{ route('panel.orders.create') }}" title="Добавить" class="add">+Добавить</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
{{--            <li class="dropdown">--}}
{{--                <a href="javascript:;" title="Страницы"><i class="icon-users"></i>Заявки</a>--}}
{{--                <ul>--}}
{{--                    <li><a class="nav-link" href="{{ route('panel.orders.index') }}">Список заявок</a></li>--}}
{{--                    <li><a class="nav-link" href="{{ route('panel.applications.index') }}">Зявки на вступление в члены МСК</a></li>--}}
{{--                    <li><a href="{{ route('panel.applications.create') }}" title="Добавить" class="add">+Добавить</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
{{--            <li class="dropdown">--}}
{{--                <a href="javascript:;" title="Справочники"><i class="icon-users"></i>Справочники</a>--}}
{{--                <ul>--}}
{{--                    @foreach($dictionaries as $dictionary)--}}
{{--                        <li class="dropdown">--}}
{{--                            <a href="javascript:;" title="{{ $dictionary->name }}"><i class="icon-users"></i>{{ $dictionary->name }}</a>--}}
{{--                            <ul>--}}
{{--                                <li><a class="nav-link" href="{{ route('panel.dictionaries.show', $dictionary) }}">Список</a></li>--}}
{{--                                <li><a href="{{ route('panel.dictionary-items.create', $dictionary) }}" title="Добавить" class="add">+Добавить</a></li>--}}
{{--                            </ul>--}}
{{--                        </li>--}}
{{--                    @endforeach--}}
{{--                </ul>--}}
{{--            </li>--}}
        </ul>
    </div>
</aside>