routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\GroupController;
use App\Http\Controllers\Admin\TimetableController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    $group = \App\Models\Group::find(1);


    return $group->timetables;
//    return [$timetable->group, $timetable->day, $timetable->time, $timetable->course, $timetable->classroom, $timetable->instructor];
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::redirect('/panel', '/panel/profile/show')->name('panel.main.url');

///** Admin Panel */
//Route::get('panel/login', [LoginController::class, 'showPanelLoginForm'])->name('panel.login');

//Route::prefix('panel')->middleware(['auth', 'role:admin|manager'])->name('panel.')->group(function ($router) {
Route::prefix('panel')->middleware(['auth'])->name('panel.')->group(function ($router) {
    /** Profile */
    $router->prefix('profile')->name('profile.')->group(function ($router) {
        $router->get('show', [ProfileController::class, 'show'])->name('show');
        $router->get('edit', [ProfileController::class, 'edit'])->name('edit');
        $router->put('edit', [ProfileController::class, 'update'])->name('update');
        $router->put('updatePassword', [ProfileController::class, 'updatePassword'])->name('updatePassword');
    });
//
//    /** Users */
    $router->resource('users', UserController::class);
    $router->put('users/{user}/updatePassword', [UserController::class, 'updatePassword'])->name('users.update_password');


    /** Groups */
    Route::resource('groups', GroupController::class);

    /** Group's Timetable */
    Route::resource('groups/{group}/timetables', TimetableController::class);

//    $router->resourse('groups', GroupController::class);
//    /** Articles */
//    $router->resource('articles', ArticlesController::class);
//
//    /** Pages */
//    $router->resource('pages', PageController::class, ['except' => ['store', 'create']]);
//    $router->post('pages/{page}/worker/add', [PageController::class, 'addWorker'])->name('pages.worker.add');
//    $router->post('pages/{page}/worker/{worker}/delete', [PageController::class, 'deleteWorker'])->name('pages.worker.delete');
//
//    /** Workers */
//    $router->resource('workers', WorkerController::class);
//
//    /** Orders */
//    $router->resource('orders', OrderController::class);

    /** Roles */
    $router->resource('roles', RoleController::class);
//
//    /** Dictionaries */
//    $router->resource('dictionaries', DictionaryController::class);
//
//    /** Dictionary Items */
//    $router->resource('dictionaries/{dictionary}/items', DictionaryItemController::class, ['names' => 'dictionary-items']);
//
//    /** Membership Applications */
//    $router->resource('applications', MembershipApplicationController::class, ['except' => ['store', 'create']]);
//    $router->put('applications/{application}/accept', [MembershipApplicationController::class, 'accept'])->name('application.accept');
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    function __construct()
    {
        $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
        $this->middleware('permission:role-create', ['only' => ['create','store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index(Request $request)
    {
        $roles = Role::orderBy('id')->paginate(5);
        return view('admin.pages.roles.index',compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        $permission = Permission::get();
        return view('admin.pages.roles.create',compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);

        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));

        return redirect()->route('panel.roles.index', [ 'lang' => \request()->segment(1)])
            ->with('success','Role created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View|Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();

        return view('admin.pages.roles.show',compact('role','rolePermissions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|View|Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();

        return view('admin.pages.roles.edit',compact('role','permission','rolePermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return RedirectResponse|Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);

        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();

        $role->syncPermissions($request->input('permission'));

        return redirect()->route('panel.roles.index')
            ->with('success','Role updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse|Response
     */
    public function destroy($id)
    {
        DB::table("roles")->where('id',$id)->delete();
        return redirect()->route('panel.roles.index')
            ->with('success','Role deleted successfully');
    }
}

resources/views/admin/pages/roles/create.blade.php
@extends('admin.layouts.index')

@section('title', 'Роли')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-4">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.roles.index') }}">Управление ролями</a></li>
                    <li><span>Создать новый роль</span></li>
                </ul>
            </div>
            <div class="col-md-8 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.roles.index') }}">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block">
        <form class="block" method="post" action="{{route('panel.roles.store') }}">
            @csrf
            <h2 class="title-primary">Роль</h2>
            <div class="input-group">
                <label class="input-group__title">Название <span class="required">*</span></label>
                <input type="text" name="name" placeholder="Название" class="input-regular" required>
            </div>
            <br>
            <div class="input-group">
                <label class="input-group__title">Возможности: </label>
                @foreach($permission as $value)
                    <label class="checkbox">
                        {{ Form::checkbox('permission[]', $value->id, false, array('class' => 'name')) }}
                        <span>{{ $value->name }}</span>
                    </label>
                @endforeach
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </form>
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection

resources/views/admin/pages/roles/edit.blade.php
@extends('admin.layouts.index')

@section('title', 'Роли')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-4">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.roles.index') }}">Управление ролями</a></li>
                    <li><span>{{ $role->name }}</span></li>
                    <li><span>Редактировать</span></li>
                </ul>
            </div>
            <div class="col-md-8 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.roles.index') }}">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block">
        {!! Form::model($role, ['method' => 'PATCH','route' => ['panel.roles.update', $role->id]]) !!}
        <div class="row">
            <input type="hidden" name="name" value="{{ $role->name }}">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="input-group">
                    <label class="input-group__title">Название:</label>
                    <input type="text" name="" placeholder="Название" class="input-regular" value="{{ $role->name }}" required disabled>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <br>
                <div class="input-group">
                    <label class="input-group__title">Возможности: </label>
                    @foreach($permission as $value)
                        <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}
                            {{ $value->name }}</label>
                        <br/>
                    @endforeach
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </div>
        {!! Form::close() !!}
        <br>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
{{--                @can('role-delete')--}}
{{--                    {!! Form::open(['method' => 'DELETE','route' => ['panel.roles.destroy', $role->id],'style'=>'display:inline']) !!}--}}
{{--                    {!! Form::submit('Delete', ['class' => 'btn btn-danger btn--red']) !!}--}}
{{--                    {!! Form::close() !!}--}}
{{--                @endcan--}}
            </div>
        </div>
    </div>

</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection

resources/views/admin/pages/roles/index.blade.php
@extends('admin.layouts.index')

@section('title', 'Роли')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-4">
                <h1 class="title-primary" style="margin-bottom: 0">Управление ролями</h1>
            </div>
            <div class="col-md-8 text-right-md text-right-lg">
                <div class="flex-form">
                    <div>
                        @can('role-create')
                            <a class="btn btn-success" href="{{ route('panel.roles.create') }}">Создать новую роль</a>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <br>
    <div class="block">
        <h2 class="title-secondary">Список ролей</h2>
        <table class="table table-records">
            <colgroup>
                <col span="1" style="width: 3%;">
                <col span="1" style="width: 55%;">
                <col span="1" style="width: 40%;">
            </colgroup>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Название</th>
                    <th>Действие</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($roles as $key => $role)
                    <tr>
                        <td>{{ ++$i }}</td>
                        <td>{{ $role->name }}</td>
                        <td>
                            <a class="btn btn-info" href="{{ route('panel.roles.show', $role->id) }}">Смотреть</a>
                            @can('role-edit')
                                <a class="btn btn-primary" href="{{ route('panel.roles.edit', $role->id) }}">Редактировать</a>
                            @endcan
{{--                            @can('role-delete')--}}
{{--                                <a href="javascript:;" title="Удалить"--}}
{{--                                   onclick="document.querySelector('#model-{{ $role->id }}').submit()"--}}
{{--                                   class="icon-btn icon-btn--pink icon-delete"></a>--}}
{{--                                <form action="{{ route('panel.roles.destroy',  $role->id) }}" id="model-{{ $role->id }}" method="post">--}}
{{--                                    @csrf--}}
{{--                                    @method('DELETE')--}}
{{--                                </form>--}}
{{--                            @endcan--}}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        {{ $roles->appends(\Illuminate\Support\Facades\Request::except('page'))->links("vendor.pagination.admin") }}
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection

resources/views/admin/pages/roles/show.blade.php
@extends('admin.layouts.index')

@section('title', 'Роли')

@section('content')

<div class="container container-fluid">
    <div class="title-block">
        <div class="row row--multiline align-items-center">
            <div class="col-md-4">
                <ul class="breadcrumbs">
                    <li><a href="{{ route('panel.roles.index') }}">Управление ролями</a></li>
                    <li><span>{{ $role->name }}</span></li>
                </ul>
            </div>
            <div class="col-md-8 text-right-md text-right-lg">
                <div class="flex-form">
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('panel.roles.index') }}">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="block">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="input-group">
                    <strong>Название:</strong>
                    {{ $role->name }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="input-group">
                    <strong>Возможности:</strong>
                    @if(!empty($rolePermissions))
                        @foreach($rolePermissions as $permission)
                            <br>
                            <label class="label label-success">{{ $permission->name }}</label>
                        @endforeach
                    @endif
                </div>
            </div>

            <div>
                @can('role-edit')
                    <a class="btn btn-primary" href="{{ route('panel.roles.edit', $role->id) }}">Редактировать</a>
                @endcan
{{--                @can('role-delete')--}}
{{--                    <a class="btn btn-danger btn--red" href="{{ route('panel.roles.destroy', $role->id) }}"--}}
{{--                       onclick="event.preventDefault();--}}
{{--                                                     document.getElementById('delete-form').submit();" title="Удалить">Удалить--}}
{{--                    </a>--}}
{{--                    <form id="delete-form" action="{{ route('panel.roles.destroy', $role->id) }}" method="POST" class="d-none">--}}
{{--                        @csrf--}}
{{--                        @method('DELETE')--}}
{{--                    </form>--}}
{{--                @endcan--}}
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
    <!--Only this page's scripts-->
    <!---->
@endsection